version: 2
updates:
- package-ecosystem: npm
  directory: "/functions"
  schedule:
    interval: daily
    time: "00:00"
    timezone: Asia/Calcutta
  open-pull-requests-limit: 99
  reviewers:
  - AravindVNair99
  assignees:
  - AravindVNair99
  ignore:
  - dependency-name: firebase-admin
    versions:
    - 9.4.2
    - 9.5.0
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
  - dependency-name: eslint-plugin-promise
    versions:
    - 4.3.0
  - dependency-name: firebase-functions
    versions:
    - 3.13.1
